import type { SupabaseClient } from '@supabase/supabase-js';

// 20-persona realistic admissions seed for the test AY.
//
// Scope: ay9999_enrolment_applications + ay9999_enrolment_status +
// ay9999_enrolment_documents ONLY. No section_students, grade_entries,
// attendance, evaluation, publications, or movements — those are exercised
// manually through the UI to validate the end-to-end workflow.
//
// Stage distribution: 7 Submitted / 6 Ongoing Verification / 4 Processing /
// 1 Cancelled / 2 Withdrawn.  Zero Enrolled — the operator drives those flips.
//
// Coverage: KD #60 doc-status discipline; KD #61 STP-conditional slots
// (E990003/005/009/014); KD #69 single-parent gate (E990003 fatherEmail null);
// KD #62 category ↔ enroleeType mirror.
//
// Idempotent on enroleeNumber — re-running skips rows that already exist.

const PDF_URL =
  'https://vnhklhppftebbcuupfjw.supabase.co/storage/v1/object/public/parent-portal/ay2025/documents/1766798602565_Sample%20document.pdf';
const PDF_URL_2 =
  'https://vnhklhppftebbcuupfjw.supabase.co/storage/v1/object/public/parent-portal/ay2025/documents/1766798631690_merged.pdf';
const IMAGE_URL =
  'https://vnhklhppftebbcuupfjw.supabase.co/storage/v1/object/public/parent-portal/ay2027/documents/1774407491653_favicon.png';

const SEEDER_ACTOR = 'seeder@demo.com';

function isoDateOffset(days: number): string {
  return new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
}

function prefixFor(ayCode: string): string {
  return `ay${ayCode.replace(/^AY/i, '').toLowerCase()}`;
}

// ─── Types ───────────────────────────────────────────────────────────────────

type Sibling = {
  fullName: string;
  birthDay: string;
  religion: string;
  educationOccupation: string;
  schoolCompany: string;
};

type DocFill = {
  status: string | null;
  url: string | null;
  expiryDays?: number | null;
};

type ParentDetail = {
  fullName: string;
  firstName: string;
  lastName: string;
  middleName?: string | null;
  birthDay: string;
  passport?: string | null;
  passportExpiry?: string | null;
  nric?: string | null;
  pass?: string | null;
  passExpiry?: string | null;
  companyName?: string | null;
  position?: string | null;
  nationality: string;
  religion: string;
  mobile: number;
  email: string | null;
  marital: 'Married' | 'Single' | 'Divorced' | 'Widowed' | 'Separated';
};

type Persona = {
  // IDs
  enroleeNumber: string;
  studentNumber: string;
  // Student identity
  firstName: string;
  middleName?: string | null;
  lastName: string;
  preferredName?: string;
  fullName: string; // LASTNAME, FIRSTNAME [MIDDLE]
  birthDay: string;
  birthPlace?: string | null;
  gender: 'Male' | 'Female';
  nationality: string;
  nric?: string | null;
  religion: string;
  religionOther?: string | null;
  primaryLanguage: string;
  // Travel docs (apps row — separate from documents table)
  passportNumber?: string | null;
  passportExpiry?: string | null;
  pass?: string | null; // pass type: DP, SP, PR, EP, LTVP, Citizen
  passExpiry?: string | null;
  passCodeStudent?: string | null;
  // Enrolment intent
  levelApplied: string;
  classType: string;
  preferredSchedule: string;
  category: 'New' | 'Current';
  parentMaritalStatus?: string | null;
  livingWithWhom: string;
  additionalLearningNeeds?: string | null;
  previousSchool?: string | null;
  // Address
  homeAddress: string;
  postalCode: number;
  homePhone?: number | null;
  contactPerson: string;
  contactPersonNumber: number;
  // Parents
  mother: ParentDetail;
  father?: ParentDetail | null;
  guardian?: ParentDetail | null;
  // Siblings (up to 3)
  siblings?: Sibling[];
  // Medical
  allergies: boolean;
  allergyDetails?: string | null;
  asthma: boolean;
  foodAllergies: boolean;
  foodAllergyDetails?: string | null;
  heartConditions: boolean;
  epilepsy: boolean;
  diabetes: boolean;
  eczema: boolean;
  otherMedicalConditions?: string | null;
  dietaryRestrictions?: string | null;
  // Avails — TEXT 'Yes'/'No', not boolean (matches DDL)
  availSchoolBus: 'Yes' | 'No';
  availUniform: 'Yes' | 'No';
  availStudentCare: 'Yes' | 'No';
  // Discounts
  discount1?: string | null;
  // Application meta
  paymentOption: string;
  contractSignatory: string;
  howDidYouKnowAboutHFSEIS: string;
  otherSource?: string | null;
  // STP (KD #61)
  stpApplicationType?: string | null;
  stpApplicationStatus?: 'Pending' | 'Submitted' | 'Approved' | 'Rejected' | null;
  residenceHistory?: unknown[] | null;
  // Consents
  socialMediaConsent: boolean;
  motherWhatsappTeamsConsent: boolean;
  fatherWhatsappTeamsConsent?: boolean | null;
  guardianWhatsappTeamsConsent?: boolean | null;
  // Pre-course acknowledgment
  preCourseAnswer: string;
  // Pipeline — SIS-side applicationStatus (7-value enum per KD #59)
  applicationStatus:
    | 'Submitted'
    | 'Ongoing Verification'
    | 'Processing'
    | 'Cancelled'
    | 'Withdrawn';
  applicationRemarks?: string | null;
  enrolmentDateOffset: number; // days from today (negative = past)
  applicationUpdateDateOffset?: number | null; // for Cancelled/Withdrawn terminal update
  // Stage tracking (offsets from today, negative = past; null = stage not reached)
  registrationStatus?: string | null;
  registrationUpdateDateOffset?: number | null;
  documentStatus?: string | null;
  documentUpdateDateOffset?: number | null;
  assessmentStatus?: string | null;
  assessmentUpdateDateOffset?: number | null;
  assessmentGradeMath?: string | null;
  assessmentGradeEnglish?: string | null;
  contractStatus?: string | null;
  contractUpdateDateOffset?: number | null;
  feeStatus?: string | null;
  feeUpdateDateOffset?: number | null;
  feeInvoiceRef?: string | null;
  feePaymentDateOffset?: number | null;
  // Documents (KD #60 status discipline)
  docs: Record<string, DocFill>;
};

// ─── 20 personas ─────────────────────────────────────────────────────────────

const PRE_COURSE_ANSWER =
  'I have read and understood the school\'s pre-course materials and agree to support my child\'s learning journey at HFSE International School.';

const PERSONAS: Persona[] = [

  // ── SUBMITTED (7) ──────────────────────────────────────────────────────────

  // 1 — Anya Krishnaswamy · YS-L · SG citizen (Indian descent) · New · Hindu
  {
    enroleeNumber: 'E990001',
    studentNumber: 'H990001',
    firstName: 'Anya',
    lastName: 'Krishnaswamy',
    fullName: 'KRISHNASWAMY, ANYA',
    birthDay: '2022-03-15',
    birthPlace: 'Singapore',
    gender: 'Female',
    nationality: 'Singapore',
    nric: 'T2234567A',
    religion: 'Hinduism',
    primaryLanguage: 'English',
    levelApplied: 'Youngstarters | Little Stars',
    classType: 'Preschool',
    preferredSchedule: 'Morning',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    homeAddress: 'Blk 456 Serangoon Avenue 2, #08-12',
    postalCode: 556012,
    homePhone: 62345678,
    contactPerson: 'Priya Krishnaswamy',
    contactPersonNumber: 91234501,
    mother: {
      fullName: 'PRIYA KRISHNASWAMY',
      firstName: 'Priya',
      lastName: 'Krishnaswamy',
      birthDay: '1988-07-22',
      passport: 'E1234501A',
      passportExpiry: isoDateOffset(1200),
      nric: 'S8867890A',
      companyName: 'Deloitte Singapore',
      position: 'Senior Consultant',
      nationality: 'Singapore',
      religion: 'Hinduism',
      mobile: 91234501,
      email: 'priya.krishnaswamy@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'VIJAY KRISHNASWAMY',
      firstName: 'Vijay',
      lastName: 'Krishnaswamy',
      birthDay: '1985-11-08',
      passport: 'E9876501A',
      passportExpiry: isoDateOffset(1500),
      nric: 'S8512345B',
      companyName: 'Accenture Singapore',
      position: 'Associate Director',
      nationality: 'Singapore',
      religion: 'Hinduism',
      mobile: 98765401,
      email: 'vijay.krishnaswamy@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Google',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Submitted',
    enrolmentDateOffset: -30,
    registrationStatus: 'Pending',
    registrationUpdateDateOffset: -30,
    docs: {
      idPicture: { status: 'Uploaded', url: IMAGE_URL },
      birthCert: { status: 'Uploaded', url: PDF_URL },
      passport: { status: 'To follow', url: null },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1200 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1500 },
    },
  },

  // 2 — Mateo Dela Cruz · YS-S · Filipino · DP · New · Catholic · sibling
  {
    enroleeNumber: 'E990002',
    studentNumber: 'H990002',
    firstName: 'Mateo',
    lastName: 'Dela Cruz',
    fullName: 'DELA CRUZ, MATEO',
    birthDay: '2021-06-22',
    birthPlace: 'Manila',
    gender: 'Male',
    nationality: 'Philippines',
    religion: 'Roman Catholic',
    primaryLanguage: 'English',
    passportNumber: 'AA1234502',
    passportExpiry: isoDateOffset(1100),
    pass: 'DP',
    passExpiry: isoDateOffset(400),
    levelApplied: 'Youngstarters | Senior Stars',
    classType: 'Preschool',
    preferredSchedule: 'Morning',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    homeAddress: '25 Toa Payoh Rise, #14-08',
    postalCode: 310025,
    homePhone: 63456789,
    contactPerson: 'Maria Dela Cruz',
    contactPersonNumber: 91234502,
    mother: {
      fullName: 'MARIA SANTOS DELA CRUZ',
      firstName: 'Maria',
      lastName: 'Dela Cruz',
      middleName: 'Santos',
      birthDay: '1990-03-14',
      passport: 'AA9876502',
      passportExpiry: isoDateOffset(1300),
      pass: 'DP',
      passExpiry: isoDateOffset(500),
      companyName: null,
      position: 'Homemaker',
      nationality: 'Philippines',
      religion: 'Roman Catholic',
      mobile: 91234502,
      email: 'maria.delacruz@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'JOSE REYES DELA CRUZ',
      firstName: 'Jose',
      lastName: 'Dela Cruz',
      middleName: 'Reyes',
      birthDay: '1987-09-30',
      passport: 'AA5678502',
      passportExpiry: isoDateOffset(1600),
      pass: 'EP',
      passExpiry: isoDateOffset(700),
      companyName: 'Shell Eastern Petroleum',
      position: 'Engineer',
      nationality: 'Philippines',
      religion: 'Roman Catholic',
      mobile: 98765402,
      email: 'jose.delacruz@demo.com',
      marital: 'Married',
    },
    siblings: [
      {
        fullName: 'Sofia Dela Cruz',
        birthDay: '2018-11-05',
        religion: 'Roman Catholic',
        educationOccupation: 'Student',
        schoolCompany: 'HFSE International School',
      },
    ],
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'Yes',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Friend',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Submitted',
    enrolmentDateOffset: -14,
    registrationStatus: 'Pending',
    registrationUpdateDateOffset: -14,
    docs: {
      idPicture: { status: 'Uploaded', url: IMAGE_URL },
      birthCert: { status: 'Uploaded', url: PDF_URL },
      passport: { status: 'Valid', url: PDF_URL, expiryDays: 1100 },
      pass: { status: 'Valid', url: PDF_URL, expiryDays: 400 },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1300 },
      motherPass: { status: 'Valid', url: PDF_URL, expiryDays: 500 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1600 },
      fatherPass: { status: 'To follow', url: null },
    },
  },

  // 3 — Zara Binte Hassan · P1 · Malaysian · DP · New · Muslim
  //     STP Pending · SINGLE PARENT (fatherEmail null → KD #69 gates father doc slots)
  {
    enroleeNumber: 'E990003',
    studentNumber: 'H990003',
    firstName: 'Zara',
    lastName: 'Hassan',
    fullName: 'HASSAN, ZARA BINTE',
    birthDay: '2019-08-10',
    birthPlace: 'Kuala Lumpur',
    gender: 'Female',
    nationality: 'Malaysia',
    religion: 'Islam',
    primaryLanguage: 'Malay',
    passportNumber: 'A12345030',
    passportExpiry: isoDateOffset(800),
    pass: 'DP',
    passExpiry: isoDateOffset(350),
    levelApplied: 'Primary One',
    classType: 'Global Class 2 (ENGLISH + CHINESE)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Single',
    livingWithWhom: 'Mother',
    additionalLearningNeeds: null,
    homeAddress: 'Blk 88 Bedok North Street 4, #03-22',
    postalCode: 460088,
    homePhone: 64567890,
    contactPerson: 'Noorlailah Hassan',
    contactPersonNumber: 91234503,
    mother: {
      fullName: 'NOORLAILAH BINTE HASSAN',
      firstName: 'Noorlailah',
      lastName: 'Hassan',
      birthDay: '1989-05-18',
      passport: 'A98765030',
      passportExpiry: isoDateOffset(900),
      pass: 'EP',
      passExpiry: isoDateOffset(500),
      companyName: 'Majlis Ugama Islam Singapura',
      position: 'Executive',
      nationality: 'Malaysia',
      religion: 'Islam',
      mobile: 91234503,
      email: 'noorlailah.hassan@demo.com',
      marital: 'Single',
    },
    father: null,
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    dietaryRestrictions: 'Halal food only',
    availSchoolBus: 'Yes',
    availUniform: 'Yes',
    availStudentCare: 'Yes',
    paymentOption: 'Option 1',
    contractSignatory: 'Mother',
    howDidYouKnowAboutHFSEIS: 'Facebook',
    stpApplicationType: 'New Student Pass Application',
    stpApplicationStatus: 'Pending',
    residenceHistory: [
      { country: 'Malaysia', fromYear: 2019, toYear: 2022, address: 'Kuala Lumpur, Malaysia' },
      { country: 'Singapore', fromYear: 2022, toYear: 'Present', address: 'Bedok, Singapore' },
    ],
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: null,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Submitted',
    enrolmentDateOffset: -21,
    registrationStatus: 'Pending',
    registrationUpdateDateOffset: -21,
    docs: {
      idPicture: { status: 'Uploaded', url: IMAGE_URL },
      birthCert: { status: 'Uploaded', url: PDF_URL },
      passport: { status: 'Valid', url: PDF_URL, expiryDays: 800 },
      pass: { status: 'To follow', url: null },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 900 },
      motherPass: { status: 'To follow', url: null },
      // father doc slots stay NULL — KD #69 (fatherEmail null)
      // STP-conditional slots (KD #61)
      icaPhoto: { status: 'Uploaded', url: IMAGE_URL },
      financialSupportDocs: { status: 'Uploaded', url: PDF_URL },
      vaccinationInformation: { status: 'To follow', url: null },
    },
  },

  // 4 — Lucas Tan · P2 · SG citizen (Chinese) · Current · Buddhist · sibling
  {
    enroleeNumber: 'E990004',
    studentNumber: 'H990004',
    firstName: 'Lucas',
    lastName: 'Tan',
    fullName: 'TAN, LUCAS WEI XIANG',
    birthDay: '2018-11-25',
    birthPlace: 'Singapore',
    gender: 'Male',
    nationality: 'Singapore',
    nric: 'T1823456B',
    religion: 'Buddhism',
    primaryLanguage: 'English',
    levelApplied: 'Primary Two',
    classType: 'Global Class 2 (ENGLISH + CHINESE)',
    preferredSchedule: 'Whole Day',
    category: 'Current',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'HFSE International School',
    homeAddress: 'Blk 301 Tampines Street 32, #10-05',
    postalCode: 520301,
    homePhone: 65678901,
    contactPerson: 'Mei Lin Tan',
    contactPersonNumber: 91234504,
    mother: {
      fullName: 'MEI LIN TAN',
      firstName: 'Mei Lin',
      lastName: 'Tan',
      birthDay: '1986-02-14',
      passport: 'E2345604A',
      passportExpiry: isoDateOffset(1100),
      nric: 'S8623456C',
      companyName: 'Ministry of Education',
      position: 'Senior Teacher',
      nationality: 'Singapore',
      religion: 'Buddhism',
      mobile: 91234504,
      email: 'meiling.tan@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'WEI JIE TAN',
      firstName: 'Wei Jie',
      lastName: 'Tan',
      birthDay: '1984-08-09',
      passport: 'E8765604A',
      passportExpiry: isoDateOffset(1400),
      nric: 'S8434567D',
      companyName: 'DBS Bank',
      position: 'Vice President, Technology',
      nationality: 'Singapore',
      religion: 'Buddhism',
      mobile: 98765404,
      email: 'weijie.tan@demo.com',
      marital: 'Married',
    },
    siblings: [
      {
        fullName: 'Sophia Tan Wei Xin',
        birthDay: '2015-04-18',
        religion: 'Buddhism',
        educationOccupation: 'Student',
        schoolCompany: 'HFSE International School',
      },
    ],
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Sibling',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Submitted',
    enrolmentDateOffset: -10,
    registrationStatus: 'Pending',
    registrationUpdateDateOffset: -10,
    docs: {
      idPicture: { status: 'Uploaded', url: IMAGE_URL },
      birthCert: { status: 'Uploaded', url: PDF_URL },
      educCert: { status: 'To follow', url: null },
      motherPassport: { status: 'To follow', url: null },
      fatherPassport: { status: 'To follow', url: null },
    },
  },

  // 5 — Kavya Sharma · P3 · Indian · DP · New · Hindu · STP Submitted · asthma
  {
    enroleeNumber: 'E990005',
    studentNumber: 'H990005',
    firstName: 'Kavya',
    lastName: 'Sharma',
    fullName: 'SHARMA, KAVYA',
    birthDay: '2017-04-18',
    birthPlace: 'Mumbai',
    gender: 'Female',
    nationality: 'India',
    religion: 'Hinduism',
    primaryLanguage: 'English',
    passportNumber: 'B2345605',
    passportExpiry: isoDateOffset(600),
    pass: 'DP',
    passExpiry: isoDateOffset(280),
    levelApplied: 'Primary Three',
    classType: 'Global Class 1 (ENGLISH ONLY)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    homeAddress: '18 Bishan Street 13, #12-34',
    postalCode: 579818,
    contactPerson: 'Sunita Sharma',
    contactPersonNumber: 91234505,
    mother: {
      fullName: 'SUNITA SHARMA',
      firstName: 'Sunita',
      lastName: 'Sharma',
      birthDay: '1987-09-03',
      passport: 'B9876505',
      passportExpiry: isoDateOffset(1100),
      pass: 'DP',
      passExpiry: isoDateOffset(400),
      companyName: null,
      position: 'Homemaker',
      nationality: 'India',
      religion: 'Hinduism',
      mobile: 91234505,
      email: 'sunita.sharma@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'RAJESH SHARMA',
      firstName: 'Rajesh',
      lastName: 'Sharma',
      birthDay: '1984-12-20',
      passport: 'B5678505',
      passportExpiry: isoDateOffset(1400),
      pass: 'EP',
      passExpiry: isoDateOffset(700),
      companyName: 'Tata Consultancy Services',
      position: 'Principal Architect',
      nationality: 'India',
      religion: 'Hinduism',
      mobile: 98765405,
      email: 'rajesh.sharma@demo.com',
      marital: 'Married',
    },
    asthma: true,
    allergies: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    otherMedicalConditions: 'Uses Ventolin inhaler. School has been notified and inhaler is kept in school bag at all times.',
    availSchoolBus: 'Yes',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Google',
    stpApplicationType: 'New Student Pass Application',
    stpApplicationStatus: 'Submitted',
    residenceHistory: [
      { country: 'India', fromYear: 2017, toYear: 2019, address: 'Mumbai, Maharashtra, India' },
      { country: 'Singapore', fromYear: 2019, toYear: 'Present', address: 'Bishan, Singapore' },
    ],
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Submitted',
    enrolmentDateOffset: -35,
    registrationStatus: 'Pending',
    registrationUpdateDateOffset: -35,
    docs: {
      idPicture: { status: 'Uploaded', url: IMAGE_URL },
      birthCert: { status: 'Uploaded', url: PDF_URL },
      passport: { status: 'Valid', url: PDF_URL, expiryDays: 600 },
      pass: { status: 'To follow', url: null },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1100 },
      motherPass: { status: 'Valid', url: PDF_URL, expiryDays: 400 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1400 },
      fatherPass: { status: 'Valid', url: PDF_URL, expiryDays: 300 },
      // STP-conditional (KD #61)
      icaPhoto: { status: 'Uploaded', url: IMAGE_URL },
      financialSupportDocs: { status: 'To follow', url: null },
      vaccinationInformation: { status: 'Uploaded', url: PDF_URL },
    },
  },

  // 6 — Benjamin Ong · P4 · SG citizen · New · Christian · guardian present · asthma
  {
    enroleeNumber: 'E990006',
    studentNumber: 'H990006',
    firstName: 'Benjamin',
    lastName: 'Ong',
    fullName: 'ONG, BENJAMIN',
    birthDay: '2016-07-03',
    birthPlace: 'Singapore',
    gender: 'Male',
    nationality: 'Singapore',
    nric: 'T1634567C',
    religion: 'Christianity',
    primaryLanguage: 'English',
    levelApplied: 'Primary Four',
    classType: 'Global Class 1 (ENGLISH ONLY)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Guardian',
    additionalLearningNeeds: null,
    homeAddress: '10 Woodlands Drive 75, #06-28',
    postalCode: 737710,
    homePhone: 66789012,
    contactPerson: 'James Lee',
    contactPersonNumber: 91234506,
    mother: {
      fullName: 'SANDRA ONG',
      firstName: 'Sandra',
      lastName: 'Ong',
      birthDay: '1985-06-12',
      passport: 'E3456706A',
      passportExpiry: isoDateOffset(1200),
      nric: 'S8556789E',
      companyName: 'Singapore Airlines',
      position: 'Cabin Crew Supervisor',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 91234506,
      email: 'sandra.ong@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'DAVID ONG',
      firstName: 'David',
      lastName: 'Ong',
      birthDay: '1983-02-28',
      passport: 'E7654706A',
      passportExpiry: isoDateOffset(1500),
      nric: 'S8312345F',
      companyName: 'Singapore Airlines',
      position: 'Pilot',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 98765406,
      email: 'david.ong@demo.com',
      marital: 'Married',
    },
    guardian: {
      fullName: 'JAMES LEE',
      firstName: 'James',
      lastName: 'Lee',
      birthDay: '1980-09-15',
      nric: 'S8089012G',
      companyName: 'Self-employed',
      position: 'Business Owner',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 91234507,
      email: 'james.lee.guardian@demo.com',
      marital: 'Married',
    },
    asthma: true,
    allergies: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    otherMedicalConditions: 'Mild asthma, managed with daily Pulmicort inhaler. Has reliever inhaler in bag.',
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Guardian',
    howDidYouKnowAboutHFSEIS: 'Walk-in',
    socialMediaConsent: false,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    guardianWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Submitted',
    enrolmentDateOffset: -25,
    registrationStatus: 'Pending',
    registrationUpdateDateOffset: -25,
    docs: {
      idPicture: { status: 'Uploaded', url: IMAGE_URL },
      birthCert: { status: 'Uploaded', url: PDF_URL },
      motherPassport: { status: 'To follow', url: null },
      fatherPassport: { status: 'To follow', url: null },
      guardianPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1000 },
    },
  },

  // 7 — Aisha Binte Mohd Razif · P5 · SG citizen (Malay) · New · Muslim
  {
    enroleeNumber: 'E990007',
    studentNumber: 'H990007',
    firstName: 'Aisha',
    lastName: 'Mohd Razif',
    fullName: 'MOHD RAZIF, AISHA BINTE',
    birthDay: '2015-09-28',
    birthPlace: 'Singapore',
    gender: 'Female',
    nationality: 'Singapore',
    nric: 'T1545678D',
    religion: 'Islam',
    primaryLanguage: 'Malay',
    levelApplied: 'Primary Five',
    classType: 'Global Class 1 (ENGLISH ONLY)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    homeAddress: 'Blk 112 Bukit Merah View, #05-18',
    postalCode: 151112,
    homePhone: 67890123,
    contactPerson: 'Haslinah Binte Ibrahim',
    contactPersonNumber: 91234508,
    mother: {
      fullName: 'HASLINAH BINTE IBRAHIM',
      firstName: 'Haslinah',
      lastName: 'Ibrahim',
      birthDay: '1984-01-09',
      nric: 'S8456789H',
      companyName: 'Mendaki',
      position: 'Programme Manager',
      nationality: 'Singapore',
      religion: 'Islam',
      mobile: 91234508,
      email: 'haslinah.ibrahim@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'MOHD RAZIF BIN ABDUL KARIM',
      firstName: 'Mohd Razif',
      lastName: 'Abdul Karim',
      birthDay: '1981-06-24',
      nric: 'S8123456I',
      companyName: 'ST Engineering',
      position: 'Engineering Manager',
      nationality: 'Singapore',
      religion: 'Islam',
      mobile: 98765408,
      email: 'mohd.razif@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    dietaryRestrictions: 'Halal food only',
    availSchoolBus: 'Yes',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Friend',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Submitted',
    enrolmentDateOffset: -18,
    registrationStatus: 'Pending',
    registrationUpdateDateOffset: -18,
    docs: {
      idPicture: { status: 'Uploaded', url: IMAGE_URL },
      birthCert: { status: 'Uploaded', url: PDF_URL },
      passport: { status: 'To follow', url: null },
      motherPassport: { status: 'To follow', url: null },
      fatherPassport: { status: 'To follow', url: null },
    },
  },

  // ── ONGOING VERIFICATION (6) ────────────────────────────────────────────────

  // 8 — Ryan Chen · P6 · SG citizen · New · Buddhist · eczema · birthCert Rejected
  {
    enroleeNumber: 'E990008',
    studentNumber: 'H990008',
    firstName: 'Ryan',
    lastName: 'Chen',
    fullName: 'CHEN, RYAN',
    birthDay: '2014-01-15',
    birthPlace: 'Singapore',
    gender: 'Male',
    nationality: 'Singapore',
    nric: 'T1412345E',
    religion: 'Buddhism',
    primaryLanguage: 'English',
    levelApplied: 'Primary Six',
    classType: 'Global Class 2 (ENGLISH + CHINESE)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    homeAddress: 'Blk 204 Ang Mo Kio Avenue 1, #11-03',
    postalCode: 560204,
    homePhone: 68901234,
    contactPerson: 'Hui Ling Chen',
    contactPersonNumber: 91234509,
    mother: {
      fullName: 'HUI LING CHEN',
      firstName: 'Hui Ling',
      lastName: 'Chen',
      birthDay: '1982-08-27',
      passport: 'E4567809A',
      passportExpiry: isoDateOffset(1500),
      nric: 'S8278901J',
      companyName: 'Raffles Medical',
      position: 'Head Nurse',
      nationality: 'Singapore',
      religion: 'Buddhism',
      mobile: 91234509,
      email: 'huiling.chen@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'JUN KAI CHEN',
      firstName: 'Jun Kai',
      lastName: 'Chen',
      birthDay: '1979-04-11',
      passport: 'E6543809A',
      passportExpiry: isoDateOffset(1800),
      nric: 'S7934567K',
      companyName: 'OCBC Bank',
      position: 'Head of Risk Management',
      nationality: 'Singapore',
      religion: 'Buddhism',
      mobile: 98765409,
      email: 'junkai.chen@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: true,
    otherMedicalConditions: 'Mild eczema on arms. Uses moisturiser daily. No medication required during school hours.',
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Google',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Ongoing Verification',
    enrolmentDateOffset: -45,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -40,
    documentStatus: 'Incomplete',
    documentUpdateDateOffset: -30,
    assessmentStatus: 'Pending',
    assessmentUpdateDateOffset: -30,
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Rejected', url: PDF_URL_2 },
      passport: { status: 'Valid', url: PDF_URL, expiryDays: 1200 },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1500 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1800 },
    },
  },

  // 9 — Natasha Gupta · S1 · Indian · SP · New · Hindu · STP Approved
  {
    enroleeNumber: 'E990009',
    studentNumber: 'H990009',
    firstName: 'Natasha',
    lastName: 'Gupta',
    fullName: 'GUPTA, NATASHA',
    birthDay: '2013-03-22',
    birthPlace: 'New Delhi',
    gender: 'Female',
    nationality: 'India',
    religion: 'Hinduism',
    primaryLanguage: 'English',
    passportNumber: 'B3456609',
    passportExpiry: isoDateOffset(900),
    pass: 'SP',
    passExpiry: isoDateOffset(330),
    levelApplied: 'Secondary One',
    classType: 'Global Class 1 (ENGLISH ONLY)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'Delhi Public School, R.K. Puram',
    homeAddress: '5 Grange Road, #02-12',
    postalCode: 249571,
    contactPerson: 'Anita Gupta',
    contactPersonNumber: 91234510,
    mother: {
      fullName: 'ANITA GUPTA',
      firstName: 'Anita',
      lastName: 'Gupta',
      birthDay: '1980-11-04',
      passport: 'B8765609',
      passportExpiry: isoDateOffset(1100),
      pass: 'DP',
      passExpiry: isoDateOffset(500),
      companyName: null,
      position: 'Homemaker',
      nationality: 'India',
      religion: 'Hinduism',
      mobile: 91234510,
      email: 'anita.gupta@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'SURESH GUPTA',
      firstName: 'Suresh',
      lastName: 'Gupta',
      birthDay: '1977-07-16',
      passport: 'B5432609',
      passportExpiry: isoDateOffset(1300),
      pass: 'EP',
      passExpiry: isoDateOffset(800),
      companyName: 'Google Asia Pacific',
      position: 'Senior Engineering Director',
      nationality: 'India',
      religion: 'Hinduism',
      mobile: 98765410,
      email: 'suresh.gupta@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    stpApplicationType: 'New Student Pass Application',
    stpApplicationStatus: 'Approved',
    residenceHistory: [
      { country: 'India', fromYear: 2013, toYear: 2021, address: 'New Delhi, India' },
      { country: 'Singapore', fromYear: 2021, toYear: 'Present', address: 'Grange Road, Singapore' },
    ],
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Google',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Ongoing Verification',
    enrolmentDateOffset: -55,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -50,
    documentStatus: 'Pending',
    documentUpdateDateOffset: -40,
    assessmentStatus: 'Pending',
    assessmentUpdateDateOffset: -40,
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Valid', url: PDF_URL },
      educCert: { status: 'Valid', url: PDF_URL },
      passport: { status: 'Valid', url: PDF_URL, expiryDays: 900 },
      pass: { status: 'To follow', url: null },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1100 },
      motherPass: { status: 'Valid', url: PDF_URL, expiryDays: 500 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1300 },
      fatherPass: { status: 'To follow', url: null },
      // STP-conditional — Approved, docs should be valid (KD #61)
      icaPhoto: { status: 'Valid', url: IMAGE_URL },
      financialSupportDocs: { status: 'Valid', url: PDF_URL },
      vaccinationInformation: { status: 'Valid', url: PDF_URL },
    },
  },

  // 10 — Gabriel Wong · S2 · SG citizen · Current · Buddhist · passport EXPIRED (expiryDays:-30)
  {
    enroleeNumber: 'E990010',
    studentNumber: 'H990010',
    firstName: 'Gabriel',
    lastName: 'Wong',
    fullName: 'WONG, GABRIEL KENG SOON',
    birthDay: '2012-06-17',
    birthPlace: 'Singapore',
    gender: 'Male',
    nationality: 'Singapore',
    nric: 'T1223456F',
    religion: 'Buddhism',
    primaryLanguage: 'English',
    passportNumber: 'E5678910A',
    passportExpiry: isoDateOffset(-30),
    levelApplied: 'Secondary Two',
    classType: 'Global Class 2 (ENGLISH + CHINESE)',
    preferredSchedule: 'Whole Day',
    category: 'Current',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'HFSE International School',
    homeAddress: 'Blk 503 Hougang Avenue 8, #09-16',
    postalCode: 530503,
    homePhone: 69012345,
    contactPerson: 'Li Shan Wong',
    contactPersonNumber: 91234511,
    mother: {
      fullName: 'LI SHAN WONG',
      firstName: 'Li Shan',
      lastName: 'Wong',
      birthDay: '1979-12-03',
      passport: 'E7891011A',
      passportExpiry: isoDateOffset(1400),
      nric: 'S7989012L',
      companyName: 'Singapore Tourism Board',
      position: 'Senior Manager',
      nationality: 'Singapore',
      religion: 'Buddhism',
      mobile: 91234511,
      email: 'lishan.wong@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'KENG BOON WONG',
      firstName: 'Keng Boon',
      lastName: 'Wong',
      birthDay: '1976-03-25',
      passport: 'E2345011A',
      passportExpiry: isoDateOffset(1600),
      nric: 'S7645678M',
      companyName: 'Sembcorp Industries',
      position: 'General Manager, Projects',
      nationality: 'Singapore',
      religion: 'Buddhism',
      mobile: 98765411,
      email: 'kengboon.wong@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Sibling',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Ongoing Verification',
    enrolmentDateOffset: -60,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -55,
    documentStatus: 'Pending',
    documentUpdateDateOffset: -45,
    assessmentStatus: 'Pending',
    assessmentUpdateDateOffset: -45,
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Valid', url: PDF_URL },
      educCert: { status: 'Uploaded', url: PDF_URL_2 },
      // expiryDays: -30 → freshen-document-statuses.ts auto-flips to 'Expired'
      passport: { status: 'Valid', url: PDF_URL, expiryDays: -30 },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1400 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1600 },
    },
  },

  // 11 — Isabelle Koh · S3 · SG citizen · Current · Christian · diabetes
  {
    enroleeNumber: 'E990011',
    studentNumber: 'H990011',
    firstName: 'Isabelle',
    lastName: 'Koh',
    fullName: 'KOH, ISABELLE',
    birthDay: '2011-08-09',
    birthPlace: 'Singapore',
    gender: 'Female',
    nationality: 'Singapore',
    nric: 'T1134567G',
    religion: 'Christianity',
    primaryLanguage: 'English',
    levelApplied: 'Secondary Three',
    classType: 'Global Class 1 (ENGLISH ONLY)',
    preferredSchedule: 'Whole Day',
    category: 'Current',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'HFSE International School',
    homeAddress: '30 Thomson Road, #08-09',
    postalCode: 307590,
    contactPerson: 'Siew Peng Koh',
    contactPersonNumber: 91234512,
    mother: {
      fullName: 'SIEW PENG KOH',
      firstName: 'Siew Peng',
      lastName: 'Koh',
      birthDay: '1977-05-31',
      passport: 'E8912311A',
      passportExpiry: isoDateOffset(1300),
      nric: 'S7756789N',
      companyName: 'National University Hospital',
      position: 'Registered Nurse, Senior',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 91234512,
      email: 'siewpeng.koh@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'BOON TAT KOH',
      firstName: 'Boon Tat',
      lastName: 'Koh',
      birthDay: '1974-10-18',
      passport: 'E1234111A',
      passportExpiry: isoDateOffset(1700),
      nric: 'S7423456O',
      companyName: 'Koh & Partners Legal',
      position: 'Senior Partner',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 98765412,
      email: 'boontat.koh@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: true,
    eczema: false,
    otherMedicalConditions: 'Type 1 Diabetes. Uses insulin pump. School has been briefed and glucagon kit is kept with the form teacher. Parent to be contacted immediately for readings below 4.0 mmol/L.',
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Sibling',
    socialMediaConsent: false,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Ongoing Verification',
    enrolmentDateOffset: -50,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -45,
    documentStatus: 'Incomplete',
    documentUpdateDateOffset: -35,
    assessmentStatus: 'Pending',
    assessmentUpdateDateOffset: -35,
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Valid', url: PDF_URL },
      educCert: { status: 'Uploaded', url: PDF_URL_2 },
      passport: { status: 'To follow', url: null },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1300 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1700 },
    },
  },

  // 12 — Xavier Lim · S4 · SG citizen · New · Christianity · heart condition
  {
    enroleeNumber: 'E990012',
    studentNumber: 'H990012',
    firstName: 'Xavier',
    lastName: 'Lim',
    fullName: 'LIM, XAVIER CHENG HUAT',
    birthDay: '2010-12-04',
    birthPlace: 'Singapore',
    gender: 'Male',
    nationality: 'Singapore',
    nric: 'T1012345H',
    religion: 'Christianity',
    primaryLanguage: 'English',
    levelApplied: 'Secondary Four',
    classType: 'Global Class 1 (ENGLISH ONLY)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'Anglo-Chinese School (Independent)',
    homeAddress: 'Blk 415 Yishun Ring Road, #07-21',
    postalCode: 760415,
    homePhone: 67654321,
    contactPerson: 'Ai Ling Lim',
    contactPersonNumber: 91234513,
    mother: {
      fullName: 'AI LING LIM',
      firstName: 'Ai Ling',
      lastName: 'Lim',
      birthDay: '1975-07-20',
      passport: 'E2341212A',
      passportExpiry: isoDateOffset(1200),
      nric: 'S7567890P',
      companyName: 'Parkway Pantai',
      position: 'Finance Director',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 91234513,
      email: 'ailing.lim@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'CHENG HUAT LIM',
      firstName: 'Cheng Huat',
      lastName: 'Lim',
      birthDay: '1972-02-14',
      passport: 'E7892112A',
      passportExpiry: isoDateOffset(1500),
      nric: 'S7234567Q',
      companyName: 'Lim Brothers Construction',
      position: 'Managing Director',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 98765413,
      email: 'chenghuat.lim@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: true,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    otherMedicalConditions: 'Repaired VSD (Ventricular Septal Defect) — cleared for full physical activity by cardiologist as of January 2025. Annual follow-up with KKH Cardiology.',
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 2',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Google',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Ongoing Verification',
    enrolmentDateOffset: -65,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -60,
    documentStatus: 'Pending',
    documentUpdateDateOffset: -50,
    assessmentStatus: 'Pending',
    assessmentUpdateDateOffset: -50,
    docs: {
      idPicture: { status: 'Uploaded', url: IMAGE_URL },
      birthCert: { status: 'Valid', url: PDF_URL },
      educCert: { status: 'Uploaded', url: PDF_URL_2 },
      passport: { status: 'Valid', url: PDF_URL, expiryDays: 1500 },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1200 },
      fatherPassport: { status: 'Rejected', url: PDF_URL_2 },
    },
  },

  // 13 — Mei Lin Huang · CS1 (Year 8) · Malaysian · DP · New · Buddhist · food allergies
  {
    enroleeNumber: 'E990013',
    studentNumber: 'H990013',
    firstName: 'Mei Lin',
    lastName: 'Huang',
    fullName: 'HUANG, MEI LIN',
    birthDay: '2012-02-26',
    birthPlace: 'Johor Bahru',
    gender: 'Female',
    nationality: 'Malaysia',
    religion: 'Buddhism',
    primaryLanguage: 'Chinese',
    passportNumber: 'A23456130',
    passportExpiry: isoDateOffset(700),
    pass: 'DP',
    passExpiry: isoDateOffset(600),
    levelApplied: 'Cambridge Secondary One (Year 8)',
    classType: 'Global Class (CAMBRIDGE)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'Sri Munsyi Abdullah Secondary School, Johor Bahru',
    homeAddress: 'Blk 712 Woodlands Drive 70, #03-07',
    postalCode: 730712,
    homePhone: 66543210,
    contactPerson: 'Xiao Mei Huang',
    contactPersonNumber: 91234514,
    mother: {
      fullName: 'XIAO MEI HUANG',
      firstName: 'Xiao Mei',
      lastName: 'Huang',
      birthDay: '1978-10-12',
      passport: 'A98765130',
      passportExpiry: isoDateOffset(900),
      pass: 'DP',
      passExpiry: isoDateOffset(500),
      companyName: null,
      position: 'Homemaker',
      nationality: 'Malaysia',
      religion: 'Buddhism',
      mobile: 91234514,
      email: 'xiaomei.huang@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'GUO WEI HUANG',
      firstName: 'Guo Wei',
      lastName: 'Huang',
      birthDay: '1975-05-08',
      passport: 'A54321130',
      passportExpiry: isoDateOffset(1100),
      pass: 'EP',
      passExpiry: isoDateOffset(800),
      companyName: 'Wilmar International',
      position: 'Regional Controller',
      nationality: 'Malaysia',
      religion: 'Buddhism',
      mobile: 98765414,
      email: 'guowei.huang@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: true,
    foodAllergyDetails: 'Severe seafood allergy, particularly shellfish. Carries EpiPen at all times. Do NOT serve any dishes containing crab, prawn, lobster, or shellfish.',
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'Yes',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Facebook',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Ongoing Verification',
    enrolmentDateOffset: -40,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -36,
    documentStatus: 'Pending',
    documentUpdateDateOffset: -28,
    assessmentStatus: 'Pending',
    assessmentUpdateDateOffset: -28,
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Uploaded', url: PDF_URL_2 },
      educCert: { status: 'Uploaded', url: PDF_URL_2 },
      passport: { status: 'Valid', url: PDF_URL, expiryDays: 700 },
      pass: { status: 'Valid', url: PDF_URL, expiryDays: 600 },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 900 },
      motherPass: { status: 'Valid', url: PDF_URL, expiryDays: 500 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1100 },
      fatherPass: { status: 'Valid', url: PDF_URL, expiryDays: 400 },
    },
  },

  // ── PROCESSING (4) ─────────────────────────────────────────────────────────

  // 14 — Rajan Kumar · CS2 (Year 9) · Indian · DP · New · Hindu · STP Rejected
  {
    enroleeNumber: 'E990014',
    studentNumber: 'H990014',
    firstName: 'Rajan',
    lastName: 'Kumar',
    fullName: 'KUMAR, RAJAN',
    birthDay: '2011-10-01',
    birthPlace: 'Chennai',
    gender: 'Male',
    nationality: 'India',
    religion: 'Hinduism',
    primaryLanguage: 'English',
    passportNumber: 'B4567814',
    passportExpiry: isoDateOffset(1000),
    pass: 'DP',
    passExpiry: isoDateOffset(450),
    levelApplied: 'Cambridge Secondary Two (Year 9)',
    classType: 'Global Class (CAMBRIDGE)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'Chennai Public School',
    homeAddress: '12 Nassim Road, #03-05',
    postalCode: 258374,
    contactPerson: 'Meena Kumar',
    contactPersonNumber: 91234515,
    mother: {
      fullName: 'MEENA KUMAR',
      firstName: 'Meena',
      lastName: 'Kumar',
      birthDay: '1976-04-22',
      passport: 'B8765814',
      passportExpiry: isoDateOffset(1200),
      pass: 'DP',
      passExpiry: isoDateOffset(600),
      companyName: null,
      position: 'Homemaker',
      nationality: 'India',
      religion: 'Hinduism',
      mobile: 91234515,
      email: 'meena.kumar@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'ARUN KUMAR',
      firstName: 'Arun',
      lastName: 'Kumar',
      birthDay: '1973-01-30',
      passport: 'B2345814',
      passportExpiry: isoDateOffset(1400),
      pass: 'EP',
      passExpiry: isoDateOffset(900),
      companyName: 'McKinsey & Company',
      position: 'Partner',
      nationality: 'India',
      religion: 'Hinduism',
      mobile: 98765415,
      email: 'arun.kumar@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    stpApplicationType: 'New Student Pass Application',
    stpApplicationStatus: 'Rejected',
    residenceHistory: [
      { country: 'India', fromYear: 2011, toYear: 2020, address: 'Chennai, Tamil Nadu, India' },
      { country: 'Singapore', fromYear: 2020, toYear: 'Present', address: 'Nassim Road, Singapore' },
    ],
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Google',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Processing',
    enrolmentDateOffset: -80,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -75,
    documentStatus: 'Finished',
    documentUpdateDateOffset: -65,
    assessmentStatus: 'Finished',
    assessmentUpdateDateOffset: -55,
    assessmentGradeMath: 'A',
    assessmentGradeEnglish: 'B+',
    contractStatus: 'Generated',
    contractUpdateDateOffset: -40,
    feeStatus: 'Invoiced',
    feeUpdateDateOffset: -35,
    feeInvoiceRef: 'INV-2026-0014',
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Valid', url: PDF_URL },
      educCert: { status: 'Valid', url: PDF_URL },
      passport: { status: 'Valid', url: PDF_URL, expiryDays: 1000 },
      pass: { status: 'To follow', url: null },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1200 },
      motherPass: { status: 'Valid', url: PDF_URL, expiryDays: 600 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1400 },
      fatherPass: { status: 'Valid', url: PDF_URL, expiryDays: 700 },
      // STP-conditional — Rejected, but docs were already collected (KD #61)
      icaPhoto: { status: 'Valid', url: IMAGE_URL },
      financialSupportDocs: { status: 'Valid', url: PDF_URL },
      vaccinationInformation: { status: 'Valid', url: PDF_URL },
    },
  },

  // 15 — Chloe Tan · P1 · SG citizen · New · Christian · sibling discount · contract Signed / fee Paid
  {
    enroleeNumber: 'E990015',
    studentNumber: 'H990015',
    firstName: 'Chloe',
    lastName: 'Tan',
    fullName: 'TAN, CHLOE',
    birthDay: '2020-02-14',
    birthPlace: 'Singapore',
    gender: 'Female',
    nationality: 'Singapore',
    nric: 'T2012345I',
    religion: 'Christianity',
    primaryLanguage: 'English',
    levelApplied: 'Primary One',
    classType: 'Global Class 1 (ENGLISH ONLY)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    homeAddress: 'Blk 67 Choa Chu Kang Loop, #08-14',
    postalCode: 689867,
    homePhone: 67891234,
    contactPerson: 'Wan Ting Tan',
    contactPersonNumber: 91234516,
    mother: {
      fullName: 'WAN TING TAN',
      firstName: 'Wan Ting',
      lastName: 'Tan',
      birthDay: '1986-11-28',
      passport: 'E3451515A',
      passportExpiry: isoDateOffset(1100),
      nric: 'S8645678R',
      companyName: 'CapitaLand',
      position: 'Retail Operations Manager',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 91234516,
      email: 'wanting.tan@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'KIAN HUAT TAN',
      firstName: 'Kian Huat',
      lastName: 'Tan',
      birthDay: '1983-05-19',
      passport: 'E7891515A',
      passportExpiry: isoDateOffset(1400),
      nric: 'S8312678S',
      companyName: 'Singapore Police Force',
      position: 'Superintendent',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 98765416,
      email: 'kianhuat.tan@demo.com',
      marital: 'Married',
    },
    siblings: [
      {
        fullName: 'Ethan Tan Kian Wei',
        birthDay: '2015-08-22',
        religion: 'Christianity',
        educationOccupation: 'Student',
        schoolCompany: 'HFSE International School',
      },
    ],
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    discount1: 'SIBLING-10',
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'Yes',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Sibling',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Processing',
    enrolmentDateOffset: -90,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -85,
    documentStatus: 'Finished',
    documentUpdateDateOffset: -75,
    assessmentStatus: 'Finished',
    assessmentUpdateDateOffset: -60,
    assessmentGradeMath: 'A',
    assessmentGradeEnglish: 'A',
    contractStatus: 'Signed',
    contractUpdateDateOffset: -45,
    feeStatus: 'Paid',
    feeUpdateDateOffset: -40,
    feeInvoiceRef: 'INV-2026-0015',
    feePaymentDateOffset: -40,
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Valid', url: PDF_URL },
      passport: { status: 'To follow', url: null },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1100 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1400 },
    },
  },

  // 16 — Damien Goh · S3 · SG citizen · Current · No Religion · contract Sent / fee Invoiced
  {
    enroleeNumber: 'E990016',
    studentNumber: 'H990016',
    firstName: 'Damien',
    lastName: 'Goh',
    fullName: 'GOH, DAMIEN',
    birthDay: '2011-05-20',
    birthPlace: 'Singapore',
    gender: 'Male',
    nationality: 'Singapore',
    nric: 'T1112345J',
    religion: 'No Religion',
    primaryLanguage: 'English',
    levelApplied: 'Secondary Three',
    classType: 'Global Class 2 (ENGLISH + CHINESE)',
    preferredSchedule: 'Whole Day',
    category: 'Current',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'HFSE International School',
    homeAddress: 'Blk 328 Bukit Batok Street 33, #05-12',
    postalCode: 650328,
    homePhone: 65678234,
    contactPerson: 'Luan Luan Goh',
    contactPersonNumber: 91234517,
    mother: {
      fullName: 'LUAN LUAN GOH',
      firstName: 'Luan Luan',
      lastName: 'Goh',
      birthDay: '1978-03-16',
      passport: 'E1231616A',
      passportExpiry: isoDateOffset(1300),
      nric: 'S7834567T',
      companyName: 'POSB',
      position: 'Branch Manager',
      nationality: 'Singapore',
      religion: 'No Religion',
      mobile: 91234517,
      email: 'luanluan.goh@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'SWEE KENG GOH',
      firstName: 'Swee Keng',
      lastName: 'Goh',
      birthDay: '1975-09-04',
      passport: 'E4561616A',
      passportExpiry: isoDateOffset(1600),
      nric: 'S7523456U',
      companyName: 'HDB',
      position: 'Assistant Director, Estates',
      nationality: 'Singapore',
      religion: 'No Religion',
      mobile: 98765417,
      email: 'sweekeng.goh@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Sibling',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Processing',
    enrolmentDateOffset: -75,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -70,
    documentStatus: 'Finished',
    documentUpdateDateOffset: -60,
    assessmentStatus: 'Finished',
    assessmentUpdateDateOffset: -50,
    assessmentGradeMath: 'B+',
    assessmentGradeEnglish: 'A',
    contractStatus: 'Sent',
    contractUpdateDateOffset: -35,
    feeStatus: 'Invoiced',
    feeUpdateDateOffset: -30,
    feeInvoiceRef: 'INV-2026-0016',
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Valid', url: PDF_URL },
      educCert: { status: 'Valid', url: PDF_URL },
      passport: { status: 'To follow', url: null },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1300 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1600 },
    },
  },

  // 17 — Siti Binte Rashid · S2 · SG citizen (Malay) · New · Muslim · contract Generated / fee Invoiced
  {
    enroleeNumber: 'E990017',
    studentNumber: 'H990017',
    firstName: 'Siti',
    lastName: 'Rashid',
    fullName: 'RASHID, SITI BINTE',
    birthDay: '2012-09-14',
    birthPlace: 'Singapore',
    gender: 'Female',
    nationality: 'Singapore',
    nric: 'T1245678K',
    religion: 'Islam',
    primaryLanguage: 'Malay',
    levelApplied: 'Secondary Two',
    classType: 'Global Class 1 (ENGLISH ONLY)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'Ahmad Ibrahim Secondary School',
    homeAddress: 'Blk 807 Yishun Street 81, #04-09',
    postalCode: 760807,
    homePhone: 67654987,
    contactPerson: 'Rohana Binte Yusof',
    contactPersonNumber: 91234518,
    mother: {
      fullName: 'ROHANA BINTE YUSOF',
      firstName: 'Rohana',
      lastName: 'Yusof',
      birthDay: '1979-07-08',
      nric: 'S7956789V',
      companyName: 'NTUC FairPrice',
      position: 'Area Supervisor',
      nationality: 'Singapore',
      religion: 'Islam',
      mobile: 91234518,
      email: 'rohana.yusof@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'RASHID BIN MOHAMED',
      firstName: 'Rashid',
      lastName: 'Mohamed',
      birthDay: '1976-04-23',
      nric: 'S7612345W',
      companyName: 'SMRT',
      position: 'Station Manager',
      nationality: 'Singapore',
      religion: 'Islam',
      mobile: 98765418,
      email: 'rashid.mohamed@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    dietaryRestrictions: 'Halal food only',
    availSchoolBus: 'Yes',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 2',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Facebook',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Processing',
    enrolmentDateOffset: -70,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -65,
    documentStatus: 'Finished',
    documentUpdateDateOffset: -55,
    assessmentStatus: 'Finished',
    assessmentUpdateDateOffset: -45,
    assessmentGradeMath: 'B',
    assessmentGradeEnglish: 'B+',
    contractStatus: 'Generated',
    contractUpdateDateOffset: -30,
    feeStatus: 'Invoiced',
    feeUpdateDateOffset: -25,
    feeInvoiceRef: 'INV-2026-0017',
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Valid', url: PDF_URL },
      educCert: { status: 'Valid', url: PDF_URL },
      passport: { status: 'To follow', url: null },
      motherPassport: { status: 'To follow', url: null },
      fatherPassport: { status: 'To follow', url: null },
    },
  },

  // ── CANCELLED (1) ──────────────────────────────────────────────────────────

  // 18 — Fabian Dela Cruz · YS-J · Filipino · DP · New · Catholic · Cancelled
  {
    enroleeNumber: 'E990018',
    studentNumber: 'H990018',
    firstName: 'Fabian',
    lastName: 'Dela Cruz',
    fullName: 'DELA CRUZ, FABIAN',
    birthDay: '2022-10-05',
    birthPlace: 'Manila',
    gender: 'Male',
    nationality: 'Philippines',
    religion: 'Roman Catholic',
    primaryLanguage: 'English',
    passportNumber: 'AA5678180',
    passportExpiry: isoDateOffset(800),
    pass: 'DP',
    passExpiry: isoDateOffset(300),
    levelApplied: 'Youngstarters | Junior Stars',
    classType: 'Preschool',
    preferredSchedule: 'Morning',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    homeAddress: '3 Farrer Road, #09-22',
    postalCode: 268831,
    contactPerson: 'Rosario Dela Cruz',
    contactPersonNumber: 91234519,
    mother: {
      fullName: 'ROSARIO GARCIA DELA CRUZ',
      firstName: 'Rosario',
      lastName: 'Dela Cruz',
      middleName: 'Garcia',
      birthDay: '1991-08-17',
      passport: 'AA9876180',
      passportExpiry: isoDateOffset(1000),
      pass: 'DP',
      passExpiry: isoDateOffset(400),
      companyName: null,
      position: 'Homemaker',
      nationality: 'Philippines',
      religion: 'Roman Catholic',
      mobile: 91234519,
      email: 'rosario.delacruz@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'EDUARDO REYES DELA CRUZ',
      firstName: 'Eduardo',
      lastName: 'Dela Cruz',
      middleName: 'Reyes',
      birthDay: '1988-02-12',
      passport: 'AA3456180',
      passportExpiry: isoDateOffset(1200),
      pass: 'EP',
      passExpiry: isoDateOffset(500),
      companyName: 'Chevron Singapore',
      position: 'Senior Petroleum Engineer',
      nationality: 'Philippines',
      religion: 'Roman Catholic',
      mobile: 98765419,
      email: 'eduardo.delacruz@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Friend',
    socialMediaConsent: false,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Cancelled',
    applicationRemarks: 'Family relocated to overseas posting prior to start of academic year. Parent requested withdrawal on 2026-04-21.',
    enrolmentDateOffset: -50,
    applicationUpdateDateOffset: -25,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -46,
    documentStatus: 'Cancelled',
    documentUpdateDateOffset: -25,
    docs: {
      idPicture: { status: 'Uploaded', url: IMAGE_URL },
      birthCert: { status: 'Uploaded', url: PDF_URL },
      passport: { status: 'Valid', url: PDF_URL, expiryDays: 800 },
      pass: { status: 'Valid', url: PDF_URL, expiryDays: 300 },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1000 },
      motherPass: { status: 'Valid', url: PDF_URL, expiryDays: 400 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1200 },
      fatherPass: { status: 'Valid', url: PDF_URL, expiryDays: 500 },
    },
  },

  // ── WITHDRAWN (2) ──────────────────────────────────────────────────────────

  // 19 — Charlotte Lee · P4 · SG citizen · Current · Christian · mid-pipeline Withdrawn
  {
    enroleeNumber: 'E990019',
    studentNumber: 'H990019',
    firstName: 'Charlotte',
    lastName: 'Lee',
    fullName: 'LEE, CHARLOTTE',
    birthDay: '2016-04-07',
    birthPlace: 'Singapore',
    gender: 'Female',
    nationality: 'Singapore',
    nric: 'T1634568L',
    religion: 'Christianity',
    primaryLanguage: 'English',
    levelApplied: 'Primary Four',
    classType: 'Global Class 1 (ENGLISH ONLY)',
    preferredSchedule: 'Whole Day',
    category: 'Current',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'HFSE International School',
    homeAddress: 'Blk 180 Toa Payoh Lorong 2, #12-06',
    postalCode: 310180,
    homePhone: 62345987,
    contactPerson: 'Sock Har Lee',
    contactPersonNumber: 91234520,
    mother: {
      fullName: 'SOCK HAR LEE',
      firstName: 'Sock Har',
      lastName: 'Lee',
      birthDay: '1983-01-25',
      passport: 'E3451919A',
      passportExpiry: isoDateOffset(1200),
      nric: 'S8312789X',
      companyName: 'Changi General Hospital',
      position: 'Medical Social Worker',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 91234520,
      email: 'sockhar.lee@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'TECK SENG LEE',
      firstName: 'Teck Seng',
      lastName: 'Lee',
      birthDay: '1980-07-14',
      passport: 'E7891919A',
      passportExpiry: isoDateOffset(1500),
      nric: 'S8034567Y',
      companyName: 'SATS Ltd',
      position: 'Operations Director',
      nationality: 'Singapore',
      religion: 'Christianity',
      mobile: 98765420,
      email: 'teckseng.lee@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Sibling',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Withdrawn',
    applicationRemarks: 'Student has decided to continue at current school and will not be transferring to HFSE for AY2027.',
    enrolmentDateOffset: -75,
    applicationUpdateDateOffset: -45,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -70,
    documentStatus: 'Finished',
    documentUpdateDateOffset: -60,
    assessmentStatus: 'Cancelled',
    assessmentUpdateDateOffset: -45,
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Valid', url: PDF_URL },
      educCert: { status: 'Uploaded', url: PDF_URL_2 },
      passport: { status: 'To follow', url: null },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1200 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1500 },
    },
  },

  // 20 — Arjun Mehta · P5 · Indian · DP · New · Hindu · late-pipeline Withdrawn (contract Generated)
  {
    enroleeNumber: 'E990020',
    studentNumber: 'H990020',
    firstName: 'Arjun',
    lastName: 'Mehta',
    fullName: 'MEHTA, ARJUN',
    birthDay: '2015-11-30',
    birthPlace: 'Mumbai',
    gender: 'Male',
    nationality: 'India',
    religion: 'Hinduism',
    primaryLanguage: 'English',
    passportNumber: 'B5678200',
    passportExpiry: isoDateOffset(1000),
    pass: 'DP',
    passExpiry: isoDateOffset(500),
    levelApplied: 'Primary Five',
    classType: 'Global Class 1 (ENGLISH ONLY)',
    preferredSchedule: 'Whole Day',
    category: 'New',
    parentMaritalStatus: 'Married',
    livingWithWhom: 'Both Parents',
    previousSchool: 'Dhirubhai Ambani International School, Mumbai',
    homeAddress: '6 Cluny Park Road, #05-03',
    postalCode: 259615,
    contactPerson: 'Pooja Mehta',
    contactPersonNumber: 91234521,
    mother: {
      fullName: 'POOJA MEHTA',
      firstName: 'Pooja',
      lastName: 'Mehta',
      birthDay: '1982-03-09',
      passport: 'B9876200',
      passportExpiry: isoDateOffset(1200),
      pass: 'DP',
      passExpiry: isoDateOffset(600),
      companyName: null,
      position: 'Homemaker',
      nationality: 'India',
      religion: 'Hinduism',
      mobile: 91234521,
      email: 'pooja.mehta@demo.com',
      marital: 'Married',
    },
    father: {
      fullName: 'SANJEEV MEHTA',
      firstName: 'Sanjeev',
      lastName: 'Mehta',
      birthDay: '1979-11-21',
      passport: 'B3456200',
      passportExpiry: isoDateOffset(1400),
      pass: 'EP',
      passExpiry: isoDateOffset(900),
      companyName: 'Reliance Industries',
      position: 'Regional Managing Director',
      nationality: 'India',
      religion: 'Hinduism',
      mobile: 98765421,
      email: 'sanjeev.mehta@demo.com',
      marital: 'Married',
    },
    allergies: false,
    asthma: false,
    foodAllergies: false,
    heartConditions: false,
    epilepsy: false,
    diabetes: false,
    eczema: false,
    availSchoolBus: 'No',
    availUniform: 'Yes',
    availStudentCare: 'No',
    paymentOption: 'Option 1',
    contractSignatory: 'Father',
    howDidYouKnowAboutHFSEIS: 'Google',
    socialMediaConsent: true,
    motherWhatsappTeamsConsent: true,
    fatherWhatsappTeamsConsent: true,
    preCourseAnswer: PRE_COURSE_ANSWER,
    applicationStatus: 'Withdrawn',
    applicationRemarks: 'Family unable to proceed with enrolment due to financial constraints. Registration fee refund requested.',
    enrolmentDateOffset: -90,
    applicationUpdateDateOffset: -60,
    registrationStatus: 'Finished',
    registrationUpdateDateOffset: -85,
    documentStatus: 'Finished',
    documentUpdateDateOffset: -75,
    assessmentStatus: 'Finished',
    assessmentUpdateDateOffset: -65,
    assessmentGradeMath: 'B+',
    assessmentGradeEnglish: 'A',
    contractStatus: 'Generated',
    contractUpdateDateOffset: -60,
    docs: {
      idPicture: { status: 'Valid', url: IMAGE_URL },
      birthCert: { status: 'Valid', url: PDF_URL },
      educCert: { status: 'Valid', url: PDF_URL },
      passport: { status: 'Valid', url: PDF_URL, expiryDays: 1000 },
      pass: { status: 'Valid', url: PDF_URL, expiryDays: 500 },
      motherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1200 },
      motherPass: { status: 'Valid', url: PDF_URL, expiryDays: 600 },
      fatherPassport: { status: 'Valid', url: PDF_URL, expiryDays: 1400 },
      fatherPass: { status: 'Valid', url: PDF_URL, expiryDays: 700 },
    },
  },
];

// ─── Export / result type ─────────────────────────────────────────────────────

export type AdmissionsMinimalResult = {
  appsInserted: number;
  statusInserted: number;
  docsInserted: number;
};

// ─── Main seed function ───────────────────────────────────────────────────────

export async function seedAdmissionsMinimal(
  service: SupabaseClient,
  testAy: { id: string; ay_code: string },
): Promise<AdmissionsMinimalResult> {
  const prefix = prefixFor(testAy.ay_code);
  const appsTable = `${prefix}_enrolment_applications`;
  const statusTable = `${prefix}_enrolment_status`;
  const docsTable = `${prefix}_enrolment_documents`;

  const { error: rpcErr } = await service.rpc('create_ay_admissions_tables', {
    p_ay_slug: prefix,
  });
  if (rpcErr) {
    throw new Error(
      `[admissions-minimal] create_ay_admissions_tables('${prefix}') failed: ${rpcErr.message}`,
    );
  }

  const { data: existingAppRows } = await service.from(appsTable).select('enroleeNumber');
  const { data: existingStatusRows } = await service.from(statusTable).select('enroleeNumber');
  const { data: existingDocsRows } = await service.from(docsTable).select('enroleeNumber');

  const existingNums = new Set<string>([
    ...((existingAppRows ?? []) as Array<{ enroleeNumber: string | null }>)
      .map((r) => r.enroleeNumber)
      .filter((n): n is string => !!n),
    ...((existingStatusRows ?? []) as Array<{ enroleeNumber: string | null }>)
      .map((r) => r.enroleeNumber)
      .filter((n): n is string => !!n),
  ]);
  const existingDocsNums = new Set<string>(
    ((existingDocsRows ?? []) as Array<{ enroleeNumber: string | null }>)
      .map((r) => r.enroleeNumber)
      .filter((n): n is string => !!n),
  );

  const newPersonas = PERSONAS.filter((p) => !existingNums.has(p.enroleeNumber));
  const newDocsPersonas = PERSONAS.filter((p) => !existingDocsNums.has(p.enroleeNumber));

  let appsInserted = 0;
  let statusInserted = 0;
  let docsInserted = 0;

  if (newPersonas.length > 0) {
    const appsRows = newPersonas.map(buildAppsRow);
    const { error: appsErr } = await service.from(appsTable).insert(appsRows);
    if (appsErr) {
      console.error(`[admissions-minimal] ${appsTable} insert failed:`, appsErr.message);
    } else {
      appsInserted = appsRows.length;
    }

    const statusRows = newPersonas.map(buildStatusRow);
    const { error: statusErr } = await service.from(statusTable).insert(statusRows);
    if (statusErr) {
      console.error(`[admissions-minimal] ${statusTable} insert failed:`, statusErr.message);
    } else {
      statusInserted = statusRows.length;
    }
  }

  if (newDocsPersonas.length > 0) {
    const docsRows = newDocsPersonas.map(buildDocsRow);
    const { error: docsErr } = await service.from(docsTable).insert(docsRows);
    if (docsErr) {
      console.error(`[admissions-minimal] ${docsTable} insert failed:`, docsErr.message);
    } else {
      docsInserted = docsRows.length;
    }
  }

  return { appsInserted, statusInserted, docsInserted };
}

// ─── Row builders ─────────────────────────────────────────────────────────────

function buildAppsRow(p: Persona): Record<string, unknown> {
  const preCourseDate = isoDateOffset(p.enrolmentDateOffset + 1);
  return {
    enroleeNumber: p.enroleeNumber,
    studentNumber: p.studentNumber,
    category: p.category,
    enroleeFullName: p.fullName,
    firstName: p.firstName,
    lastName: p.lastName,
    middleName: p.middleName ?? null,
    preferredName: p.preferredName ?? p.firstName,
    birthDay: p.birthDay,
    gender: p.gender,
    nationality: p.nationality,
    nric: p.nric ?? null,
    religion: p.religion,
    religionOther: p.religionOther ?? null,
    primaryLanguage: p.primaryLanguage,
    passportNumber: p.passportNumber ?? null,
    passportExpiry: p.passportExpiry ?? null,
    pass: p.pass ?? null,
    passExpiry: p.passExpiry ?? null,
    passCodeStudent: p.passCodeStudent ?? null,
    levelApplied: p.levelApplied,
    classType: p.classType,
    preferredSchedule: p.preferredSchedule,
    parentMaritalStatus: p.parentMaritalStatus ?? 'Married',
    livingWithWhom: p.livingWithWhom,
    additionalLearningNeeds: p.additionalLearningNeeds ?? null,
    previousSchool: p.previousSchool ?? null,
    homeAddress: p.homeAddress,
    postalCode: p.postalCode,
    homePhone: p.homePhone ?? null,
    contactPerson: p.contactPerson,
    contactPersonNumber: p.contactPersonNumber,
    // Mother
    motherFullName: p.mother.fullName,
    motherFirstName: p.mother.firstName,
    motherLastName: p.mother.lastName,
    motherMiddleName: p.mother.middleName ?? null,
    motherBirthDay: p.mother.birthDay,
    motherPassport: p.mother.passport ?? null,
    motherPassportExpiry: p.mother.passportExpiry ?? null,
    motherNric: p.mother.nric ?? null,
    motherPass: p.mother.pass ?? null,
    motherPassExpiry: p.mother.passExpiry ?? null,
    motherCompanyName: p.mother.companyName ?? null,
    motherPosition: p.mother.position ?? null,
    motherNationality: p.mother.nationality,
    motherReligion: p.mother.religion,
    motherMobile: p.mother.mobile,
    motherEmail: p.mother.email,
    motherMarital: p.mother.marital,
    // Father (KD #69: all null when fatherEmail absent)
    fatherFullName: p.father?.fullName ?? null,
    fatherFirstName: p.father?.firstName ?? null,
    fatherLastName: p.father?.lastName ?? null,
    fatherMiddleName: p.father?.middleName ?? null,
    fatherBirthDay: p.father?.birthDay ?? null,
    fatherPassport: p.father?.passport ?? null,
    fatherPassportExpiry: p.father?.passportExpiry ?? null,
    fatherNric: p.father?.nric ?? null,
    fatherPass: p.father?.pass ?? null,
    fatherPassExpiry: p.father?.passExpiry ?? null,
    fatherCompanyName: p.father?.companyName ?? null,
    fatherPosition: p.father?.position ?? null,
    fatherNationality: p.father?.nationality ?? null,
    fatherReligion: p.father?.religion ?? null,
    fatherMobile: p.father?.mobile ?? null,
    fatherEmail: p.father?.email ?? null,
    fatherMarital: p.father?.marital ?? null,
    // Guardian
    guardianFullName: p.guardian?.fullName ?? null,
    guardianFirstName: p.guardian?.firstName ?? null,
    guardianLastName: p.guardian?.lastName ?? null,
    guardianMiddleName: p.guardian?.middleName ?? null,
    guardianBirthDay: p.guardian?.birthDay ?? null,
    guardianPassport: p.guardian?.passport ?? null,
    guardianPassportExpiry: p.guardian?.passportExpiry ?? null,
    guardianNric: p.guardian?.nric ?? null,
    guardianPass: p.guardian?.pass ?? null,
    guardianPassExpiry: p.guardian?.passExpiry ?? null,
    guardianCompanyName: p.guardian?.companyName ?? null,
    guardianPosition: p.guardian?.position ?? null,
    guardianNationality: p.guardian?.nationality ?? null,
    guardianReligion: p.guardian?.religion ?? null,
    guardianMobile: p.guardian?.mobile ?? null,
    guardianEmail: p.guardian?.email ?? null,
    // Siblings (up to 3)
    siblingFullName1: p.siblings?.[0]?.fullName ?? null,
    siblingBirthDay1: p.siblings?.[0]?.birthDay ?? null,
    siblingReligion1: p.siblings?.[0]?.religion ?? null,
    siblingEducationOccupation1: p.siblings?.[0]?.educationOccupation ?? null,
    siblingSchoolCompany1: p.siblings?.[0]?.schoolCompany ?? null,
    siblingFullName2: p.siblings?.[1]?.fullName ?? null,
    siblingBirthDay2: p.siblings?.[1]?.birthDay ?? null,
    siblingReligion2: p.siblings?.[1]?.religion ?? null,
    siblingEducationOccupation2: p.siblings?.[1]?.educationOccupation ?? null,
    siblingSchoolCompany2: p.siblings?.[1]?.schoolCompany ?? null,
    siblingFullName3: p.siblings?.[2]?.fullName ?? null,
    siblingBirthDay3: p.siblings?.[2]?.birthDay ?? null,
    siblingReligion3: p.siblings?.[2]?.religion ?? null,
    siblingEducationOccupation3: p.siblings?.[2]?.educationOccupation ?? null,
    siblingSchoolCompany3: p.siblings?.[2]?.schoolCompany ?? null,
    // Medical
    allergies: p.allergies,
    allergyDetails: p.allergyDetails ?? null,
    asthma: p.asthma,
    foodAllergies: p.foodAllergies,
    foodAllergyDetails: p.foodAllergyDetails ?? null,
    heartConditions: p.heartConditions,
    epilepsy: p.epilepsy,
    diabetes: p.diabetes,
    eczema: p.eczema,
    otherMedicalConditions: p.otherMedicalConditions ?? null,
    dietaryRestrictions: p.dietaryRestrictions ?? null,
    paracetamolConsent: true,
    // Avails — TEXT 'Yes'/'No' per DDL
    availSchoolBus: p.availSchoolBus,
    availUniform: p.availUniform,
    availStudentCare: p.availStudentCare,
    // Discounts
    discount1: p.discount1 ?? null,
    discount2: null,
    discount3: null,
    // STP (KD #61)
    stpApplicationType: p.stpApplicationType ?? null,
    stpApplicationStatus: p.stpApplicationStatus ?? null,
    residenceHistory: p.residenceHistory ? JSON.stringify(p.residenceHistory) : null,
    // Parent-portal-side status — always 'Registered' for a completed form (KD #59)
    applicationStatus: 'Registered',
    paymentOption: p.paymentOption,
    contractSignatory: p.contractSignatory,
    howDidYouKnowAboutHFSEIS: p.howDidYouKnowAboutHFSEIS,
    otherSource: p.otherSource ?? null,
    // Consents
    socialMediaConsent: p.socialMediaConsent,
    motherWhatsappTeamsConsent: p.motherWhatsappTeamsConsent,
    fatherWhatsappTeamsConsent: p.fatherWhatsappTeamsConsent ?? null,
    guardianWhatsappTeamsConsent: p.guardianWhatsappTeamsConsent ?? null,
    // Pre-course
    preCourseAnswer: p.preCourseAnswer,
    preCourseDate: `${preCourseDate}T09:00:00+08:00`,
    preCourseAcknowledgedAt: `${preCourseDate}T09:15:00+08:00`,
    // Photo
    enroleePhoto: IMAGE_URL,
  };
}

function buildStatusRow(p: Persona): Record<string, unknown> {
  const updateOffset = p.applicationUpdateDateOffset ?? p.enrolmentDateOffset;
  return {
    enroleeNumber: p.enroleeNumber,
    enroleeName: p.fullName,
    enroleeType: p.category,
    levelApplied: p.levelApplied,
    enrolmentDate: isoDateOffset(p.enrolmentDateOffset),
    // SIS-side 7-value enum (KD #59)
    applicationStatus: p.applicationStatus,
    applicationRemarks: p.applicationRemarks ?? null,
    applicationUpdatedDate: isoDateOffset(updateOffset),
    applicationUpdatedBy: SEEDER_ACTOR,
    // Registration — NOTE: column is registrationUpdateDate (no trailing 'd')
    registrationStatus: p.registrationStatus ?? null,
    registrationUpdateDate:
      p.registrationUpdateDateOffset != null
        ? isoDateOffset(p.registrationUpdateDateOffset)
        : null,
    registrationUpdatedby: p.registrationStatus ? SEEDER_ACTOR : null,
    registrationRemarks: null,
    // Documents
    documentStatus: p.documentStatus ?? null,
    documentUpdatedDate:
      p.documentUpdateDateOffset != null ? isoDateOffset(p.documentUpdateDateOffset) : null,
    documentUpdatedby: p.documentStatus ? SEEDER_ACTOR : null,
    documentRemarks: null,
    // Assessment
    assessmentStatus: p.assessmentStatus ?? null,
    assessmentUpdatedDate:
      p.assessmentUpdateDateOffset != null ? isoDateOffset(p.assessmentUpdateDateOffset) : null,
    assessmentUpdatedby: p.assessmentStatus ? SEEDER_ACTOR : null,
    assessmentGradeMath: p.assessmentGradeMath ?? null,
    assessmentGradeEnglish: p.assessmentGradeEnglish ?? null,
    assessmentRemarks: null,
    assessmentMedical: null,
    assessmentSchedule:
      p.assessmentStatus === 'Finished' && p.assessmentUpdateDateOffset != null
        ? isoDateOffset(p.assessmentUpdateDateOffset)
        : null,
    // Contract
    contractStatus: p.contractStatus ?? null,
    contractUpdatedDate:
      p.contractUpdateDateOffset != null ? isoDateOffset(p.contractUpdateDateOffset) : null,
    contractUpdatedby: p.contractStatus ? SEEDER_ACTOR : null,
    contractRemarks: null,
    // Fee
    feeStatus: p.feeStatus ?? null,
    feeUpdatedDate:
      p.feeUpdateDateOffset != null ? isoDateOffset(p.feeUpdateDateOffset) : null,
    feeUpdatedby: p.feeStatus ? SEEDER_ACTOR : null,
    feeRemarks: null,
    feeInvoice: p.feeInvoiceRef ?? null,
    feePaymentDate:
      p.feePaymentDateOffset != null ? isoDateOffset(p.feePaymentDateOffset) : null,
    feeStartDate: null,
    // Class — always null (no Enrolled personas; user drives this manually)
    classStatus: null,
    classAY: null,
    classLevel: null,
    classSection: null,
    classRemarks: null,
    classUpdatedDate: null,
    classUpdatedby: null,
  };
}

// Default fill for a required slot that a persona didn't explicitly declare.
// 'To follow' = parent acknowledged but hasn't uploaded yet — the only valid
// non-null state when we don't have a real document URL to attach.
const TO_FOLLOW: DocFill = { status: 'To follow', url: null };

function buildDocsRow(p: Persona): Record<string, unknown> {
  // Merge persona docs with completeness defaults so the DB row never carries
  // a null status on a required slot (plan invariant; verified by the post-seed
  // SQL checks in the plan). The order of precedence: persona explicit > default.
  const docs: Record<string, DocFill> = { ...p.docs };

  // Student document slots — always required (KD #60).
  for (const slot of ['idPicture', 'birthCert', 'educCert', 'medical', 'form12', 'passport', 'pass']) {
    if (!docs[slot]) docs[slot] = TO_FOLLOW;
  }

  // Mother slots — always required (anchor parent, always present per KD #69).
  for (const slot of ['motherPassport', 'motherPass']) {
    if (!docs[slot]) docs[slot] = TO_FOLLOW;
  }

  // Father slots — required only when fatherEmail is set (KD #69 gate).
  if (p.father?.email) {
    for (const slot of ['fatherPassport', 'fatherPass']) {
      if (!docs[slot]) docs[slot] = TO_FOLLOW;
    }
  }

  // Guardian slots — required only when guardianEmail is set (KD #69 gate).
  if (p.guardian?.email) {
    for (const slot of ['guardianPassport', 'guardianPass']) {
      if (!docs[slot]) docs[slot] = TO_FOLLOW;
    }
  }

  const row: Record<string, unknown> = {
    enroleeNumber: p.enroleeNumber,
    studentNumber: p.studentNumber,
    idPictureUploadedDate:
      docs['idPicture']?.status === 'Uploaded' || docs['idPicture']?.status === 'Valid'
        ? isoDateOffset(p.enrolmentDateOffset)
        : null,
    uploadFormDocument: null,
  };
  for (const [key, fill] of Object.entries(docs)) {
    row[key] = fill.url;
    row[`${key}Status`] = fill.status;
    if (fill.expiryDays != null) {
      row[`${key}Expiry`] = isoDateOffset(fill.expiryDays);
    }
  }
  return row;
}

