-- 012_ay_setup_helpers.sql
--
-- AY Setup Wizard — Postgres helper functions. See docs/context/18-ay-setup.md
-- for the full design. These functions are the atomicity layer: Supabase JS
-- can't run multi-statement transactions from the client, so the compound
-- operations (create a whole AY, delete a whole AY) live here.
--
-- Security: all functions are `security definer` so they can run DDL. Execute
-- is REVOKEd from public and GRANTed only to `service_role` — the app calls
-- them exclusively via `createServiceClient()` in the API route.
--
-- Template source of truth: docs/context/10-parent-portal.md §"Reference DDL".
-- When the parent portal bumps the admissions schema, update BOTH the doc AND
-- the `create_ay_admissions_tables` function body below. lib/sis/ay-setup/
-- admissions-ddl.ts carries a TypeScript mirror for reference.
--
-- See docs/context/18-ay-setup.md §"Admissions DDL" for the coordination rule.

-- =====================================================================
-- create_ay_admissions_tables(p_ay_slug text)
-- =====================================================================
-- Creates the 4 AY-prefixed admissions tables for the given slug
-- (e.g. 'ay27'). Idempotent via CREATE TABLE IF NOT EXISTS.

create or replace function public.create_ay_admissions_tables(p_ay_slug text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slug text := lower(trim(p_ay_slug));
begin
  if v_slug !~ '^ay[0-9]{2}$' then
    raise exception 'Invalid AY slug: %. Expected format like "ay27".', p_ay_slug;
  end if;

  -- ay{YY}_enrolment_applications
  execute format($ddl$
    create table if not exists public.%I (
      id bigint generated by default as identity not null,
      created_at timestamp with time zone null default (now() at time zone 'Asia/Singapore'::text),
      category character varying null,
      "enroleeNumber" text null,
      "studentNumber" text null,
      "enroleeFullName" text null,
      "lastName" text null,
      "firstName" text null,
      "middleName" text null,
      "preferredName" text null,
      "levelApplied" text null,
      "classType" text null,
      "preferredSchedule" text null,
      "birthDay" date null,
      gender text null,
      "passportNumber" text null,
      "passportExpiry" date null,
      nationality text null,
      religion text null,
      "religionOther" text null,
      nric text null,
      pass text null,
      "passExpiry" date null,
      "homeAddress" text null,
      "postalCode" bigint null,
      "homePhone" bigint null,
      "contactPerson" text null,
      "contactPersonNumber" bigint null,
      "primaryLanguage" text null,
      "parentMaritalStatus" text null,
      "livingWithWhom" text null,
      "fatherFullName" text null, "fatherLastName" text null, "fatherFirstName" text null,
      "fatherMiddleName" text null, "fatherPreferredName" text null, "fatherBirthDay" date null,
      "fatherPassport" text null, "fatherPassportExpiry" date null, "fatherNric" text null,
      "fatherPass" text null, "fatherPassExpiry" date null, "fatherCompanyName" text null,
      "fatherPosition" text null, "fatherNationality" text null, "fatherReligion" text null,
      "fatherMobile" bigint null, "fatherEmail" text null, "fatherMarital" text null,
      "motherFullName" text null, "motherLastName" text null, "motherFirstName" text null,
      "motherMiddleName" text null, "motherPreferredName" text null, "motherBirthDay" date null,
      "motherPassport" text null, "motherPassportExpiry" date null, "motherNric" text null,
      "motherPass" text null, "motherPassExpiry" date null, "motherCompanyName" text null,
      "motherPosition" text null, "motherNationality" text null, "motherReligion" text null,
      "motherMobile" bigint null, "motherEmail" text null, "motherMarital" text null,
      "guardianFullName" text null, "guardianLastName" text null, "guardianFirstName" text null,
      "guardianMiddleName" text null, "guardianPreferredName" text null, "guardianBirthDay" date null,
      "guardianPassport" text null, "guardianPassportExpiry" date null, "guardianNric" text null,
      "guardianPass" text null, "guardianPassExpiry" date null, "guardianCompanyName" text null,
      "guardianPosition" text null, "guardianNationality" text null, "guardianReligion" text null,
      "guardianMobile" bigint null, "guardianEmail" text null,
      "siblingFullName1" text null, "siblingBirthDay1" date null, "siblingReligion1" text null,
      "siblingEducationOccupation1" text null, "siblingSchoolCompany1" text null,
      "siblingFullName2" text null, "siblingBirthDay2" date null, "siblingReligion2" text null,
      "siblingEducationOccupation2" text null, "siblingSchoolCompany2" text null,
      "siblingFullName3" text null, "siblingBirthDay3" date null, "siblingReligion3" text null,
      "siblingEducationOccupation3" text null, "siblingSchoolCompany3" text null,
      "siblingFullName4" text null, "siblingBirthDay4" date null, "siblingReligion4" text null,
      "siblingEducationOccupation4" text null, "siblingSchoolCompany4" text null,
      "siblingFullName5" text null, "siblingBirthDay5" date null, "siblingReligion5" text null,
      "siblingEducationOccupation5" text null, "siblingSchoolCompany5" text null,
      "availSchoolBus" text null, "availUniform" text null, "availStudentCare" text null,
      "additionalLearningNeeds" text null, "previousSchool" text null,
      "documentsStatus" text null, "registrationInvoice" text null,
      "registrationInvoiceDate" date null, "assessmentDate" date null,
      "assessmentStatus" text null, "startDate" text null,
      "enrollmentInvoice" text null, "enrollmentInvoiceDate" date null,
      "acctsRemarks" text null, "enroleePhoto" text null, "creatorUid" text null,
      "howDidYouKnowAboutHFSEIS" text null, "otherSource" text null,
      "applicationStatus" text null,
      "fatherReligionOther" text null, "motherReligionOther" text null, "guardianReligionOther" text null,
      "passCodeStudent" text null,
      discount1 text null, discount2 text null, discount3 text null,
      "referrerName" text null, "paymentOption" text null, "referrerMobile" text null,
      "contractSignatory" text null, "vizSchoolProgram" text null,
      "feedbackRating" smallint null, "feedbackComments" text null,
      "feedbackConsent" boolean null, "feedbackSubmittedAt" timestamp without time zone null,
      "preCourseAnswer" text null, "preCourseDate" timestamp without time zone null,
      "preCourseAcknowledgedAt" timestamp without time zone null,
      "stpApplicationType" text null,
      allergies boolean null, "allergyDetails" text null, asthma boolean null,
      "foodAllergies" boolean null, "foodAllergyDetails" text null,
      "heartConditions" boolean null, epilepsy boolean null, diabetes boolean null, eczema boolean null,
      "otherMedicalConditions" text null, "paracetamolConsent" boolean null,
      "otherLearningNeeds" text null, "studentCareProgram" text null,
      "socialMediaConsent" boolean null,
      "guardianWhatsappTeamsConsent" boolean null,
      "fatherWhatsappTeamsConsent" boolean null,
      "motherWhatsappTeamsConsent" boolean null,
      "residenceHistory" jsonb null,
      "dietaryRestrictions" text null,
      constraint %I primary key (id)
    );
  $ddl$, v_slug || '_enrolment_applications', v_slug || '_enrolment_applications_pkey');

  -- ay{YY}_enrolment_status
  execute format($ddl$
    create table if not exists public.%I (
      id bigint generated by default as identity not null,
      created_at timestamp with time zone not null default now(),
      "enroleeNumber" text null,
      "enrolmentDate" date null,
      "enroleeName" text null,
      "applicationStatus" character varying null,
      "applicationRemarks" text null,
      "applicationUpdatedDate" date null,
      "applicationUpdatedBy" text null,
      "registrationStatus" character varying null,
      "registrationInvoice" text null,
      "registrationPaymentDate" date null,
      "registrationRemarks" text null,
      "registrationUpdateDate" date null,
      "registrationUpdatedby" text null,
      "documentStatus" character varying null,
      "documentRemarks" text null,
      "documentUpdatedDate" date null,
      "documentUpdatedby" text null,
      "assessmentStatus" character varying null,
      "assessmentSchedule" date null,
      "assessmentGradeMath" text null,
      "assessmentGradeEnglish" text null,
      "assessmentRemarks" text null,
      "assessmentMedical" text null,
      "assessmentUpdatedDate" date null,
      "assessmentUpdatedby" text null,
      "contractStatus" character varying null,
      "contractRemarks" text null,
      "contractUpdatedDate" date null,
      "contractUpdatedby" text null,
      "feeStatus" character varying null,
      "feeInvoice" text null,
      "feePaymentDate" date null,
      "feeStartDate" date null,
      "feeRemarks" text null,
      "feeUpdatedDate" date null,
      "feeUpdatedby" text null,
      "classStatus" character varying null,
      "classAY" character varying null,
      "classLevel" character varying null,
      "classSection" character varying null,
      "classRemarks" text null,
      "classUpdatedDate" date null,
      "classUpdatedby" text null,
      "suppliesStatus" character varying null,
      "suppliesClaimedDate" date null,
      "suppliesRemarks" text null,
      "suppliesUpdatedDate" date null,
      "suppliesUpdatedby" text null,
      "orientationStatus" character varying null,
      "orientationScheduleDate" date null,
      "orientationRemarks" text null,
      "orientationUpdatedDate" date null,
      "orientationUpdateby" text null,
      "enroleeType" character varying null,
      "levelApplied" text null,
      constraint %I primary key (id)
    );
  $ddl$, v_slug || '_enrolment_status', v_slug || '_enrolment_status_pkey');

  -- ay{YY}_enrolment_documents
  execute format($ddl$
    create table if not exists public.%I (
      id bigint generated by default as identity not null,
      created_at timestamp with time zone null default (now() at time zone 'Asia/Singapore'::text),
      "studentNumber" text null,
      "enroleeNumber" text null,
      form12 text null, "form12Status" character varying null,
      medical text null, "medicalStatus" character varying null,
      passport text null, "passportStatus" character varying null, "passportExpiry" date null,
      "birthCert" text null, "birthCertStatus" character varying null,
      pass text null, "passStatus" character varying null, "passExpiry" date null,
      "educCert" text null, "educCertStatus" character varying null,
      "motherPassport" text null, "motherPassportStatus" character varying null, "motherPassportExpiry" date null,
      "motherPass" text null, "motherPassStatus" character varying null, "motherPassExpiry" date null,
      "fatherPassport" text null, "fatherPassportStatus" character varying null, "fatherPassportExpiry" date null,
      "fatherPass" text null, "fatherPassStatus" character varying null, "fatherPassExpiry" date null,
      "guardianPassport" text null, "guardianPassportStatus" character varying null, "guardianPassportExpiry" date null,
      "guardianPass" text null, "guardianPassStatus" character varying null, "guardianPassExpiry" date null,
      "idPicture" text null, "idPictureStatus" character varying null, "idPictureUploadedDate" date null,
      "uploadFormDocument" uuid null,
      "icaPhoto" text null, "icaPhotoStatus" character varying null,
      "financialSupportDocs" text null, "financialSupportDocsStatus" character varying null,
      "vaccinationInformation" text null, "vaccinationInformationStatus" character varying null,
      constraint %I primary key (id)
    );
  $ddl$, v_slug || '_enrolment_documents', v_slug || '_enrolment_documents_pkey');

  -- ay{YY}_discount_codes
  execute format($ddl$
    create table if not exists public.%I (
      id bigint generated by default as identity not null,
      created_at timestamp with time zone not null default now(),
      "discountCode" text null,
      "startDate" date null,
      "endDate" date null,
      details text null,
      "enroleeType" character varying null,
      constraint %I primary key (id)
    );
  $ddl$, v_slug || '_discount_codes', v_slug || '_discount_codes_pkey');
end;
$$;

revoke all on function public.create_ay_admissions_tables(text) from public;
grant execute on function public.create_ay_admissions_tables(text) to service_role;

-- =====================================================================
-- drop_ay_admissions_tables(p_ay_slug text)
-- =====================================================================
-- Drops the 4 AY-prefixed admissions tables. Pre-flight guards verify
-- every target has zero rows; raises if any are populated. Idempotent
-- via DROP TABLE IF EXISTS.

create or replace function public.drop_ay_admissions_tables(p_ay_slug text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slug       text := lower(trim(p_ay_slug));
  v_table      text;
  v_rowcount   bigint;
  v_tables     text[] := array[
    'enrolment_applications',
    'enrolment_status',
    'enrolment_documents',
    'discount_codes'
  ];
begin
  if v_slug !~ '^ay[0-9]{2}$' then
    raise exception 'Invalid AY slug: %. Expected format like "ay27".', p_ay_slug;
  end if;

  foreach v_table in array v_tables loop
    if to_regclass(format('public.%I', v_slug || '_' || v_table)) is not null then
      execute format('select count(*) from public.%I', v_slug || '_' || v_table)
        into v_rowcount;
      if v_rowcount > 0 then
        raise exception 'Cannot drop %_%: table has % rows. Refusing to destroy data.',
          v_slug, v_table, v_rowcount;
      end if;
    end if;
  end loop;

  execute format('drop table if exists public.%I', v_slug || '_enrolment_documents');
  execute format('drop table if exists public.%I', v_slug || '_enrolment_status');
  execute format('drop table if exists public.%I', v_slug || '_enrolment_applications');
  execute format('drop table if exists public.%I', v_slug || '_discount_codes');
end;
$$;

revoke all on function public.drop_ay_admissions_tables(text) from public;
grant execute on function public.drop_ay_admissions_tables(text) to service_role;

-- =====================================================================
-- create_academic_year(p_ay_code text, p_label text)
-- =====================================================================
-- Atomically creates everything a new AY needs to function inside the SIS:
--   1. Inserts a row into academic_years (is_current=false).
--   2. Inserts 4 terms (T1–T4) with NULL dates.
--   3. Copies sections from the most-recent prior AY (by ay_code desc).
--   4. Copies subject_configs from the most-recent prior AY.
--   5. Creates the 4 AY-prefixed admissions tables (via helper above).
--
-- Returns JSON: { ay_id, sections_copied, subject_configs_copied,
--                 terms_created, tables_created }.
-- Raises on duplicate ay_code or invalid format.

create or replace function public.create_academic_year(
  p_ay_code text,
  p_label   text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code             text := upper(trim(p_ay_code));
  v_label            text := trim(p_label);
  v_slug             text;
  v_ay_id            uuid;
  v_source_ay_id     uuid;
  v_sections_copied  int;
  v_configs_copied   int;
begin
  if v_code !~ '^AY[0-9]{4}$' then
    raise exception 'Invalid AY code: %. Expected format AY2027.', p_ay_code;
  end if;
  if v_label is null or v_label = '' then
    raise exception 'AY label is required.';
  end if;

  v_slug := 'ay' || substring(v_code from 5 for 2);

  -- 1. academic_years row
  insert into public.academic_years (ay_code, label, is_current)
  values (v_code, v_label, false)
  returning id into v_ay_id;

  -- 2. terms (T1–T4, nullable dates)
  insert into public.terms (academic_year_id, term_number, label, is_current)
  select v_ay_id, n, 'Term ' || n || ' — ' || v_code, false
  from generate_series(1, 4) as g(n);

  -- 3. Pick source AY for copy-forward: most recent by ay_code desc,
  --    excluding the one we just inserted.
  select id into v_source_ay_id
  from public.academic_years
  where id <> v_ay_id
  order by ay_code desc
  limit 1;

  if v_source_ay_id is not null then
    -- Copy sections
    insert into public.sections (academic_year_id, level_id, name, class_type, form_class_adviser)
    select v_ay_id, level_id, name, class_type, null
    from public.sections
    where academic_year_id = v_source_ay_id;

    get diagnostics v_sections_copied = row_count;

    -- Copy subject_configs
    insert into public.subject_configs (
      academic_year_id, subject_id, level_id,
      ww_weight, pt_weight, qa_weight, ww_max_slots, pt_max_slots
    )
    select v_ay_id, subject_id, level_id,
           ww_weight, pt_weight, qa_weight, ww_max_slots, pt_max_slots
    from public.subject_configs
    where academic_year_id = v_source_ay_id;

    get diagnostics v_configs_copied = row_count;
  else
    v_sections_copied := 0;
    v_configs_copied  := 0;
  end if;

  -- 4. Admissions DDL
  perform public.create_ay_admissions_tables(v_slug);

  return jsonb_build_object(
    'ay_id', v_ay_id,
    'ay_code', v_code,
    'ay_slug', v_slug,
    'terms_created', 4,
    'sections_copied', v_sections_copied,
    'subject_configs_copied', v_configs_copied,
    'tables_created', jsonb_build_array(
      v_slug || '_enrolment_applications',
      v_slug || '_enrolment_status',
      v_slug || '_enrolment_documents',
      v_slug || '_discount_codes'
    )
  );
end;
$$;

revoke all on function public.create_academic_year(text, text) from public;
grant execute on function public.create_academic_year(text, text) to service_role;

-- =====================================================================
-- delete_academic_year(p_ay_code text)
-- =====================================================================
-- Atomically deletes an AY if and only if it has no data anywhere.
-- Guards:
--   - Not is_current.
--   - No section_students for any section in this AY.
--   - No grading_sheets for any term in this AY.
--   - No admissions rows in any of the 4 AY-prefixed tables.
--   - No p_file_revisions for this AY.
--   - No attendance_records / report_card_comments / report_card_publications /
--     grade_change_requests via the AY's sheets/terms.
--
-- If any blocker is present, raises with a descriptive message. Otherwise
-- runs the drop_ay_admissions_tables helper and deletes the SIS rows.

create or replace function public.delete_academic_year(p_ay_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code        text := upper(trim(p_ay_code));
  v_slug        text;
  v_ay_id       uuid;
  v_is_current  boolean;
  v_count       bigint;
  v_blocker     text;
  v_configs     int;
  v_sections    int;
  v_terms       int;
  v_total_rows  bigint;
begin
  if v_code !~ '^AY[0-9]{4}$' then
    raise exception 'Invalid AY code: %. Expected format AY2027.', p_ay_code;
  end if;

  v_slug := 'ay' || substring(v_code from 5 for 2);

  select id, is_current
    into v_ay_id, v_is_current
  from public.academic_years
  where ay_code = v_code;

  if v_ay_id is null then
    raise exception 'AY % not found.', v_code;
  end if;

  if v_is_current then
    raise exception 'Cannot delete % — it is the current AY. Switch active first.', v_code;
  end if;

  -- Guard: section_students
  select count(*) into v_count
  from public.section_students ss
  join public.sections s on s.id = ss.section_id
  where s.academic_year_id = v_ay_id;
  if v_count > 0 then
    v_blocker := v_count || ' section_students rows';
    raise exception 'Cannot delete %: %', v_code, v_blocker;
  end if;

  -- Guard: grading_sheets (via terms or sections in this AY)
  select count(*) into v_count
  from public.grading_sheets gs
  where gs.term_id in (select id from public.terms where academic_year_id = v_ay_id)
     or gs.section_id in (select id from public.sections where academic_year_id = v_ay_id);
  if v_count > 0 then
    v_blocker := v_count || ' grading_sheets rows';
    raise exception 'Cannot delete %: %', v_code, v_blocker;
  end if;

  -- Guard: attendance_records (via terms in this AY)
  select count(*) into v_count
  from public.attendance_records
  where term_id in (select id from public.terms where academic_year_id = v_ay_id);
  if v_count > 0 then
    v_blocker := v_count || ' attendance_records rows';
    raise exception 'Cannot delete %: %', v_code, v_blocker;
  end if;

  -- Guard: report_card_publications (via terms in this AY)
  select count(*) into v_count
  from public.report_card_publications
  where term_id in (select id from public.terms where academic_year_id = v_ay_id);
  if v_count > 0 then
    v_blocker := v_count || ' report_card_publications rows';
    raise exception 'Cannot delete %: %', v_code, v_blocker;
  end if;

  -- Guard: p_file_revisions matching this AY code
  select count(*) into v_count
  from public.p_file_revisions
  where ay_code = v_code;
  if v_count > 0 then
    v_blocker := v_count || ' p_file_revisions rows';
    raise exception 'Cannot delete %: %', v_code, v_blocker;
  end if;

  -- Guard: admissions tables populated
  v_total_rows := 0;
  if to_regclass(format('public.%I', v_slug || '_enrolment_applications')) is not null then
    execute format('select count(*) from public.%I', v_slug || '_enrolment_applications')
      into v_count;
    v_total_rows := v_total_rows + v_count;
  end if;
  if to_regclass(format('public.%I', v_slug || '_enrolment_status')) is not null then
    execute format('select count(*) from public.%I', v_slug || '_enrolment_status')
      into v_count;
    v_total_rows := v_total_rows + v_count;
  end if;
  if to_regclass(format('public.%I', v_slug || '_enrolment_documents')) is not null then
    execute format('select count(*) from public.%I', v_slug || '_enrolment_documents')
      into v_count;
    v_total_rows := v_total_rows + v_count;
  end if;
  if to_regclass(format('public.%I', v_slug || '_discount_codes')) is not null then
    execute format('select count(*) from public.%I', v_slug || '_discount_codes')
      into v_count;
    v_total_rows := v_total_rows + v_count;
  end if;
  if v_total_rows > 0 then
    raise exception 'Cannot delete %: admissions tables hold % rows total.', v_code, v_total_rows;
  end if;

  -- All guards passed — proceed with delete
  perform public.drop_ay_admissions_tables(v_slug);

  delete from public.subject_configs where academic_year_id = v_ay_id;
  get diagnostics v_configs = row_count;

  delete from public.sections where academic_year_id = v_ay_id;
  get diagnostics v_sections = row_count;

  delete from public.terms where academic_year_id = v_ay_id;
  get diagnostics v_terms = row_count;

  delete from public.academic_years where id = v_ay_id;

  return jsonb_build_object(
    'ay_code', v_code,
    'ay_slug', v_slug,
    'subject_configs_deleted', v_configs,
    'sections_deleted', v_sections,
    'terms_deleted', v_terms,
    'tables_dropped', jsonb_build_array(
      v_slug || '_enrolment_applications',
      v_slug || '_enrolment_status',
      v_slug || '_enrolment_documents',
      v_slug || '_discount_codes'
    )
  );
end;
$$;

revoke all on function public.delete_academic_year(text) from public;
grant execute on function public.delete_academic_year(text) to service_role;
